### ISSUE TITLE
Do not deviate from UBA

### ISSUE THREAD

**Issue by egmontkob** [kent-karlsson/control#16]
Under SPD, you say

> For the Unicode bidi algorithm, PDF and PDI should be interpreted as equivalent, LRE should be interpreted as LRI, RLE should be interpreted as RLI.

This is unacceptable.

The Unicode BiDi Algorithm (UBA) is a work of many people who presumably each know way more about BiDi than you (or, for that matter, I) do.

How come you take the liberty of modifying this algorithm, changing the meaning of some Unicode characters?

Have you considered the possible side effects, e.g. the text changing its layout and thus its meaning or readability, as you import from / export to, copy-paste from / to etc. your format?

Or do you wish to add this burden of fixing the payload (converting the bytes in a way that will end up with the same rendered look) into implementations; without giving them any help whatsoever in a form of an algorithm or other instructions (e.g. which codepoint to replace with which other solution), in a way that preserves the user-visible look of the text?

What problems do you have with UBA in the first place that you aim to fix here and would justify deviating from what UBA does anywhere else?

---

You continue:

> FSI should be interpreted as LRI if the character progression is left-to-right and as RLI if the character progression is right-to-left (i.e., no dependence on “first strong bidi” character for FSI, since direction needs to be predictable).

Again, one more Unicode character whose meaning, behavior you alter.

The very intent of `FSI` is to detect the directionality based on the inner contents, rather than some external piece of information. This feature was introduced in Unicode 6.3 (or so) to address an actual frequent real-life need.

Why would you think that while any other document formats can handle it correctly (i.e. they're able to invoke the UBA and do nothing more), it would cause problems or would not be good enough with _your_ particular ECMA-based format?

Why would you need the direction to be "predictable", whatever you mean by this word? If someone uses your format as a document exchange format, they immediately have access to the entire contents, they can examine it and take actions based on it.

Even in terminal emulators, where the data is not known upfront and is arrivinig continuously in tiny chunks (and it's even possible to arbitrarily overwrite some earlier characters), in order for a terminal emulator to perform _any_ BiDi whatsoever (even just the simplest shuffling without control characters), the characters need to be re-shuffled (the UBA re-run) anyway every time a new chunk of characters arrives and the display is updated. Therefore supporting `FSI` with its original intent is not any harder than supporting it with your altered intent, not even in terminal emulators. (In fact, it's easier, since then the terminal can directly hook up to the UBA without custom hacks.)

---

Then you go:

> CSI 1[ is equivalent to LRO (U+202D) if the current direction is RL and equivalent to RLO (U+202E) if the current direction is LR

How is someone supposed to hook it up to an existing UBA implementation if Unicode doesn't have this concept?

Is there really a need for this feature, aren't the features provided by Unicode enough already? If so, you should work on making it part of Unicode and UBA, then to be implemented by UBA libraries.

---

In your document you take steps to add compatibility with ISCII, an encoding which, according to its Wikipedia page, "has not been widely used outside certain government institutions" and "has now been rendered largely obsolete by Unicode". You also take steps to add compatibility with Teletext, although you admit that Unicode needs further improvement for this to work.

Yet, for scripts used by roughly 10% of the world's population, instead of adapting the modern solution that everyone else adapts, you come with some limitations, extensions and modifications to it.

I don't think you really got your priorities right.

You don't give any rationale why those modifications would be needed, or at least preferable to have.

You don't give any instructions how a text encoded according official Unicode and UBA should be adapted to your modified version. For example, what's the equivalent of `LRE` in your format? If a piece of software properly supports Unicode and UBA, and is handling a piece of text using `LRE`, what should it do when exporting to your format? (Leaving the byte sequence unmodified is obviously not a good answer because by your explicit intent it modifies (i.e. breaks) the rendered, user-visible look of the text.) Same problem in the opposite direction, where you extend the capabilities rather than limit them: How should someone import into their document a `CSI 1[` from your format?

Looking at the practical side of the story: No one who is adding BiDi support to their application is expected to code up UBA from scratch. They are expected to grab one of the several existing UBA implementations and let that do the work. If there's a variation of UBA out there, this approach can no longer work. People would have to patch an existing implementation, or implement the modified standard from scratch, or figure out how to glue up the library so that the gluing takes care of these modifications; and also figure out how to convert text from one format to the other. All this without you giving any help whatsoever (e.g. concrete algorithm, examples, let alone implementation).

I'm pretty certain that you're not familiar with BiDi's requirements any better than those who designed UBA (to be honest, probably nowhere near as much as they do). I'm pretty certain that any modification you make to UBA is unreasonable and unjustified. I'm absolutely certain that any modification makes it utterly unfeasible for any application to start supporting your modified format.

Please don't do this. Please rely on unaltered UBA.

**Comment by kent-karlsson** [comment]
It is not all that trivial to know how to process an ECMA-48 text string, including where, in the processing to
do bidi processing (if enabled). The Unicode bidi algorithm is formulated for "Pure plain text", not giving
details on how to apply it when there is styling, math expressions, or tables in the text. Since that is what
we are adding via ECMA-48 (and the separate proposal on math expressions), it is best to clarify the matter.
It is, and must be, quite far away from "just apply the Unicode bidi algorithm as is" (there is no such thing).

Note that using a "mode" setting (ECMA TR 53) for bidi "on"/"off" would be inappropriate, indeed, highly
inappropriate. In addition, all other modes are deprecated, as we should regard this one.

I've added some text about the processing steps, including where to place bidi processing, to the working draft.
Below are the steps, which gives an overview. 

Note that so-called non-characters play a significant role here. They generalise OBJECT REPLACEMENT CHARACTER.
From https://www.unicode.org/faq/private_use.html: "They are intended explicitly for internal use. For example,
they might be used internally as a particular kind of object placeholder in a string. [...]" (There are 34 of
them in the BMP (66 total). Together with OBJECT REPLACEMENT CHARACTER, there are 35 character codes in the BMP
that can be used for "object replacement" (per paragraph), and 67 in total. 67 of them (per paragraph) should be
more than sufficient, but any overflow needs to be handled, of course, but that is implementation defined
(I would suggest using OBJECT REPLACEMENT CHARACTER for any overflow objects, which are not displayed. Or start
using PUA chars for any overflow.) Non-characters can be used for other internal use than object replacement,
but that is the appropriate use here.

1.	Replace each character reference, see section 3.4, with the character it refers to. Note that ESC [ is a character reference for CSI and that CSI …_ are character references. 

2.	While parsing out paragraphs, parse out structures such as table rows (which may nest), Ruby text, math expressions (see (C1 version) https://github.com/kent-karlsson/control/
blob/main/math-layout-controls-2022-C.pdf),  hyperlinks, as well as vector graphics and images (which may be represented inline as control strings, or as img hyperlinks) in the paragraph. (Sequences of emoji+ZWJ?)
   Replace each by a unique (per paragraph) non-character, indicating which “text object” it replaces. The text objects are stored in a table per paragraph. Some text objects may contain text in turn, like table rows which has cells which have text in them; likewise for Ruby text, hyperlinks, math expressions and vector graphics (with text boxes). Note that a sequence of cells in a table row are laid out in the character progression direction.

3.	Convert LRE to LRI (the LRE replacement), RLE to RLI (the RLE replacement), FSI to LRI if the character progression is LR and to RLI if the character progression is RL (i.e., no dependence on “first strong bidi” character for FSI, since reading direction needs to be predictable; just as for the paragraph itself), and convert PDF (matching LRE/LRI/RLE/RLI) to PDI.
    Whether the legacy (ECMA-48) bidi control sequences are interpreted is implementation defined. However, this will limit the “range” of the original ECMA-48 bidi controls to each paragraph, a limitation originally not present. If implemented, CSI 0] and CSI 0[ ECMA-48 bidi control sequences, should be converted to PDF (U+202C), CSI 1] should be converted to LRO (U+202D), and CSI 2] to RLO (U+202E), CSI 1[ to LRO (U+202D) if the current direction is RL and to RLO (U+202E) if the current direction is LR.

4.	Transform styling control sequences (including styling push/pop, if implemented) into (within paragraph) non-overlapping style runs, removing the styling control sequences; however, 
CSI 0m may (implementation defined) instead be replaced by a sequence of PDF/PDI to close any open bidi control brackets. The styling of a paragraph will initially inherit the style before the paragraph; similarly for parsed out parts, such as table cells and math expressions. How a style run is represented is implementation defined but needs to be manageable when substrings are rearranged in the bidi rearrangement step; this rearrangement step may split style runs. Note that also explicit rotation, if implemented, is a styling; but the implicit rotations described below should not be seen as a styling.

5.	Convert any remaining escape sequences, control sequences, control strings, and SCI sequences as in step 2, but the stored data is just the substring as is. The style range data needs to be adjusted to these substitutions; this step may be done jointly with step 4.

6.	Apply this sequence of steps recursively as appropriate to the parsed out parts (still in the internal per paragraph lookup table; for cells in table rows it is applied to the cell content, for math expressions only apply them to identifiers and text components, for vector graphics, apply them to text components, for hyperlinks apply it to the display string part of the hyperlink (not the link part).

7.	If bidi processing is enabled, per SPD2 setting, apply the Unicode bidi algorithm level calculation to the resulting string, with non-characters for the parsed-out parts (step 2 and step 5), paragraph direction as per SPD2 setting.

8.	Compute the width (and height) of the text parts, taking into account the bidi level, glyph width (after stretch, if any) and height (both after rotation, if any), kerning and ligatures, cursive joining, and whitespace widths, (HT/HTJ/IS1 “width” need be recalculated during automatic line breaking) and compute automatic line break positions, also taking into account the generated hyphen in case of automatic or semi-automatic (SHY) hyphenation.

9.	If bidi processing is enabled, per SPD2 setting, apply the Unicode bidi algorithm reordering part, keeping track of styling spans and split them if needed based on the reordering. Treat HTJ as HT w.r.t. this reordering, and VT and FF are treated as LS.

10.	The portions of the text line (separated by line breaks and HT/HTJ), as well as HT and HTJ are laid out in the character progression direction (treating also IS1 as HT), styling as per styling run data, which has been adjusted according to bidi reordering. Table cells in a table row are also laid out in the paragraph progression direction. Math expressions are insensitive to paragraph direction setting (and to all other SPD/SPD2 settings), but sensitive to rotation (if implemented). When laying out the text line, the non-characters are replaced by the display of the text objects that were parsed out for the initial steps. It is implementation defined what is done with control sequences, control strings, etc. that are not otherwise interpreted (as bidi controls, styling controls, table rows, Ruby, math expressions, vector graphics, hyperlinks, …).

The Unicode bidi algorithm is intended for “prose” text, text that is supposed to be in natural or constructed “natural-like” languages, where there may be portions that are in an RTL script. That is for anything between tweets and novels, or, more realistically, Wikipedia pages. Applying the bidi algorithm (steps 7 and 9) “wholesale” on text that is computer source code of some kind, however, is not recommended, as the source code then might not only be hard to read, but even misleading about what the code actually is, like appear to have swapped arguments to operators which the actual execution of the code will not do, or have a misleading display order for data elements in a source data file. Therefore, CSI 0!S is strongly recommended for all kinds of computer source code, whether program or data. If one wants to have source code where elements such as identifiers, string literals, and comments are bidi processed, then an IDE should be used. An IDE editor can do programming language (or data language) parsing and apply bidi in isolation on each such element.
Further, bidi processing is not appropriate for text that is displayed in vertical lines of text, like for Mongolian or for CJK (though the latter is often presented in horizontal lines in modern texts).


In the summary (a bit long for the summary, so might be moved):

CSI 0!S Character progression left-to-right, no bidi processing. HT and HTJ as well as cells in a table row are in left-to-right order. Common default. Also used for visual order (when the bidi algorithm or a precursor thereof and shaping (using ARABIC…FORM characters) has been done separately prior to rendering). Same as CSI 0 SP S. BOL is at the left side. Suitable for most scripts (LTR, user not able to read RTL scripts). Very suitable for source code (.java, .css, .cpp, .xml, .json, .cvs, and many other kinds of computer source code) texts, especially if there is any RTL script content (no bidi processing or cursive shaping at all, in contrast to “visual order”), since it avoids bidi pitfalls that may occur for source code (but less likely for running text, “prose”).

CSI 1!S CJK/Hangul vertical, line progression right-to-left, no bidi processing but (in contrast to CSI 1 SP S) rotates non-CJK/Hangul characters, including parentheses/brackets and other punctuation. Character progression, HT and HTJ as well as cells in a table row are in top-to-bottom order. Table rows are in right-to-left order. BOL is at the top side.

CSI 2!S Mongolian vertical, line progression left-to-right, no bidi processing but  (in contrast to CSI 2 SP S) rotates non-Mongolian (and non-CJK/Hangul) characters, including parentheses/brackets/punctuation. Character progression, HT and HTJ as well as cells in a table row are in top-to-bottom order. Table rows are in left-to-right order. BOL is at the top side.

CSI 3!S Character reading direction right-to-left, with Unicode bidi processing; actually sets paragraph direction to “1” for the bidi algorithm, but “printing order” still left-to-right after bidi rearrangement and mirroring; but HT and HTJ as well as cells in a table row are in right-to-left order. BOL is at the right side. Suitable for texts in “bidi scripts” (with occasional occurrences of LTR texts, such as numerals, or Latin script phrases). Do not use for source code (.java, .json, …), as it is certain to misprint the code.

CSI 4!S, …, CSI 7!S Reserved.

CSI 8!S Character reading direction left-to-right, with Unicode bidi processing; actually sets paragraph direction to “0” for the bidi algorithm, but “printing order” still left-to-right after bidi rearrangement and mirroring; HT and HTJ as well as cells in a table row are in left-to-right order. BOL is at the left side. Suitable for (non-code) text in an “LTR script” with occasional “bidi script” phrases. Unsuitable for source code (.java, .json, .cpp, .xml, …), since it may cause misreading if RLT text occurs (in identifiers, comments, or string literals) in the source code.

CSI 10!S Boustrophedon. No bidi processing, but right-to-left text lines get all glyphs mirrored. BOL (for beginning of paragraph) is at the left side (but switches for every line of text). Historical interest.

CSI 11!S, …, CSI 98!S Reserved.

CSI 99!S Reset to default directions, per preference or default setting. Note that if an SPD(2) setting is within a table cell, a pop(!) to outer SPD(2) setting is implicit at end of cell.
