### ISSUE TITLE
Superscript and subscript

### ISSUE THREAD

**Issue by spixi** [kent-karlsson/control#19]
You are proposing the following XML tags:

* ```<lsp/>```, left superscript operator
* ```<lsb/>```, left subscript operator
* ```<rsb/>```, right subscript operator
* ```<rsp/>```, right superscript operator

XML is a markup language and most XML schemes use context-free grammars. Your notation is context-sensitive and cannot be parsed by a simple pushdown automaton. Also parallel, bottom-up and recursive rendering is impossible . You also cannot simply use XSLT transformations to convert or extract subscript / superscript values.

I would rather proposing the following XML tags:
* ```<sup></sup>```, superscript
* ```<sub> </sub>```, subscript

```2^2^2``` could be expressed as  ```2<sup>2<sup>2</sup></sup>``` and ```(2^2)^2``` as ```(2<sup>2</sup>)<sup>2</sup>```.

This also would be more consistent with your ```<me> </me>``` instead of ```<sme/> <eme/>```.

**Comment by kent-karlsson** [comment]
> You are proposing the following XML tags:
> •	&lt;lsp/>, left superscript operator
> •	&lt;lsb/>, left subscript operator
> •	&lt;rsb/>, right subscript operator
> •	&lt;rsp/>, right superscript operator
> XML is a markup language and most XML schemes use context-free grammars. Your
> notation is context-sensitive and cannot be parsed by a simple pushdown automaton.

Of course it is a context free grammar! I give both an ABNF and an LALR(1) grammar (in an appendix). 
Both are clearly context-free grammars (LALR(1) grammars is a strict subset of context free grammars). 
Context sensitive grammars are highly rare in practice. The only one I have seen in practice is the 
two-level grammar for Algol 68 (there is a context -free grammar to generate the “real” grammar for 
Algol 68; technically it is an infinite grammar, so not exactly what was defined as context-sensitive 
grammars). The grammar(s) are not regular expressions, though. Regular expressions is a strict 
subset of context-free grammars. (Parsing state is not what is counted w.r.t. context-free versus 
context sensitive grammars.)

Further, I’d like to keep the parallel as close as possible to the other (or other two) representation(s) 
presented in the paper, which in turn very much keeps the parallel to (La)TeX) (using ^ and _ as infix 
operators) and even eqn (which uses “sup” and “sub” _infix_ operators).

And… Since I propose a very tight integration with HTML (and SVG), the math expressions would 
*be* HTML (and would *be* SVG), the tags &lt;sub> and &lt;sup> would conflict with the &lt;sub> and 
&lt;sup> of “ordinary” HTML, which are similar but still different (they are not math).

> Also parallel, bottom-up and recursive rendering is impossible.

After special-purpose (in this case: math expressions of this kind) parsing it is possible. Hmm, did you 
mean “rendering” here, or “parsing”?

> You also cannot simply use XSLT transformations to convert or extract subscript / superscript values.

I don’t know if XSLT can be used or not. If XSLT can only handle regular expressions, then it is out of the question, 
since math expression layout is truly recursive, not just “tail recursive” (regular expressions).

> I would rather proposing the following XML tags:
> •	&lt;sup>&lt;/sup>, superscript
> •	&lt;sub> &lt;/sub>, subscript
> 2^2^2 could be expressed as 2&lt;sup>2&lt;sup>2&lt;/sup>&lt;/sup> and (2^2)^2 as (2&lt;sup>2&lt;/sup>)&lt;sup>2&lt;/sup>.

That is the “ordinary HTML” approach to superscripts and subscripts. Also in MathML that is done 
differently (i.e. not like in HTML).

Replacing !ENTITY:s with corresponding !ELEMENT:s (in the DTD given in the paper) will certainly 
mean very many tags to be needed, that are really derivable via (context-free, LALR(1) even) parsing.

> This also would be more consistent with your &lt;me> &lt;/me> instead of &lt;sme/> &lt;eme/>.

That the “other” approach was not used for &lt;me>, &lt;txt> and &lt;mx> is because there would be no gain 
(reduction in nr. of tags). One might just as well use the basic XML parsing. Similarly, for &lt;mc> and 
&lt;mr> the gain would be small to use the “other” approach. But for all the other layout operators, the 
“full form” direct in XML would lead to terrible tag bloat. Compare MathML and OMML which both 
suffer from tag bloat. That tag bloat, among other things, make both of them impractical.
